name: cashlink
description: Fast Peer-to-Peer Cash Exchange
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  local_auth: ^2.1.7
  provider: ^6.1.1
  image_picker: any
  firebase_storage: ^11.0.16
  js: ^0.6.7
  http: ^0.13.6
  url_launcher: ^6.2.2
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

