name: cashlink
description: Fast Peer-to-Peer Cash Exchange
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0
  google_maps_flutter: ^2.5.0
  location: ^6.0.2
  local_auth: ^2.1.7
  provider: ^6.1.1
  image_picker: ^1.0.7
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
