// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7t84pI7CqEFbsUg2C-UEz93rVeSFlXJE',
    appId: '1:834461848683:web:f8e623a027349f39510d2e',
    messagingSenderId: '834461848683',
    projectId: 'cash-link-d7395',
    authDomain: 'cash-link-d7395.firebaseapp.com',
    storageBucket: 'cash-link-d7395.firebasestorage.app',
    measurementId: 'G-W3SF9RGSBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWKiIVd-WZ2CUjxwuDhBqs1hh9iNZkP0',
    appId: '1:834461848683:android:4277882a3aa9cd99510d2e',
    messagingSenderId: '834461848683',
    projectId: 'cash-link-d7395',
    storageBucket: 'cash-link-d7395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXgdj0MA0vc59o04dzcSVk-HBfaESkj0',
    appId: '1:834461848683:ios:f559917a0c08c3e7510d2e',
    messagingSenderId: '834461848683',
    projectId: 'cash-link-d7395',
    storageBucket: 'cash-link-d7395.firebasestorage.app',
    iosBundleId: 'com.example.cashlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXgdj0MA0vc59o04dzcSVk-HBfaESkj0',
    appId: '1:834461848683:ios:f559917a0c08c3e7510d2e',
    messagingSenderId: '834461848683',
    projectId: 'cash-link-d7395',
    storageBucket: 'cash-link-d7395.firebasestorage.app',
    iosBundleId: 'com.example.cashlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7t84pI7CqEFbsUg2C-UEz93rVeSFlXJE',
    appId: '1:834461848683:web:eef3c62bc202d412510d2e',
    messagingSenderId: '834461848683',
    projectId: 'cash-link-d7395',
    authDomain: 'cash-link-d7395.firebaseapp.com',
    storageBucket: 'cash-link-d7395.firebasestorage.app',
    measurementId: 'G-HNMMBFML4K',
  );
}
