name: Build Flutter App (Android & iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: List build outputs
        run: |
          echo "APK files:"
          find build/app/outputs/flutter-apk/ -name "*.apk" || echo "No APK files found"
          echo "AAB files:"
          find build/app/outputs/bundle/ -name "*.aab" || echo "No AAB files found"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS for simulator (debug mode)
        run: flutter build ios --debug --simulator

      - name: List iOS build outputs
        run: |
          echo "iOS build outputs:"
          find build/ios/ -name "*.app" || echo "No .app files found"

      - name: Upload iOS Simulator .app
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app-debug
          path: build/ios/iphonesimulator/Runner.app

      - name: Create iOS .ipa (simulator debug)
        run: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            mkdir Payload
            cp -r build/ios/iphonesimulator/Runner.app Payload/
            zip -r ios-simulator-debug.ipa Payload
            echo "Created simulator debug IPA"
          else
            echo "No simulator app found"
          fi
        shell: bash

      - name: Upload iOS Simulator .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-ipa-debug
          path: ios-simulator-debug.ipa
        if: hashFiles('ios-simulator-debug.ipa') != ''

      - name: Attempt iOS device build (profile mode, no codesign)
        run: |
          echo "Attempting device build in profile mode..."
          flutter build ios --profile --no-codesign || echo "Device build failed - this is expected in CI without certificates"
        continue-on-error: true
